services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_inventory_db
    ports:
      - '5555:5432'
  postgres-employees:
    image: 'postgres:latest'
    container_name: 'postgres_employees'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_inventory_employees_db
    ports:
      - '5556:5432'
  frontend:
    build: ./inventory-frontend
    container_name: react_app
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
  backend:
    build: ./inventory-backend
    container_name: nest_app
    ports:
      - '3000:3000'
    environment:
      ENVIRONMENT: dev
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: tech_inventory_db
    depends_on:
      - postgres
  employees:
    build: ./inventory-people
    container_name: express_app
    ports:
      - '5050:5050'
    environment:
      DB_HOST: postgres-employees
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: tech_inventory_employees_db
      DB_MAX_CONNECTIONS: 10
      DB_IDLE_TIMEOUT: 3000
    depends_on:
      - postgres-employees